export const NAVIGATION_ROUTE = {
    LOGIN: '/login',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    FORGOT_USERNAME: 'FORGOT_USERNAME',
    OTP_VERIFICATION: 'OTP_VERIFICATION',
    RESET_PASSWORD: 'RESET_PASSWORD',
    
  };